# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/librarysys?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081
dur02:
  jwt:
    secret: f4e2e52034348f86b67cde5810f9eb5
    expire: 604800
    header: Authorization
shiro-redis:
  enable: true
  redis-manager:
    host: 127.0.0.1:6379

